### ISSUE TITLE
How to valuate models?

### ISSUE THREAD

**Issue by KongMingxi** [tencent-ailab/valuationgame#1]
Hi authors,

Congratulations and thanks for your excellent work and contributions! 
I wonder how to use this method for model valuation when I have a batch of trained models?

Best,

**Comment by yataobian** [comment]
Hi KongMingxi,

Thanks for your nice question!  

Since model valuation is also formulated as a cooperative game [1],  and the model's valuation is given as the player valuation in the cooperative game. Therefore, our method (variational values) could serve as a principled alternative for model valuations. 
I think you might be mainly wondering about how to cast model valuation as a cooperative game, for which one can refer to the details in [1] and the followup work.  

Thanks!  

[1] Rozemberczki, Benedek, and Rik Sarkar. "The shapley value of classifiers in ensemble games." In Proceedings of the 30th ACM International Conference on Information & Knowledge Management, pp. 1558-1567. 2021.
